name: Checkstyle
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  gradle:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Run Checkstyle
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: checkstyleMain